### ISSUE TITLE
image exceed 5mb error using Claude Sonnet 3.5

### ISSUE THREAD

**Issue by yurigushiken** [Cohee1207/Extension-ScreenShare#1]
I get the error when on some screens but not others. get error possibly when there's more detail in the image but not sure. 
UHD+ resolution 3840x2400 display 120hz, I don't know if that's relevant or not 
![Screenshot 2024-06-24 230745](https://github.com/SillyTavern/Extension-ScreenShare/assets/171873050/7abe02b7-b308-45cd-906b-e3706e0aa7cc)

Thank you for the extension. must-have and i greatly appreciate it

**Comment by Cohee1207** [comment]
> I don't know if that's relevant or not

Yes, it is. PNG image exceeded the limit of the API. I switched to use JPEG which should yield smaller files with negligible quality loss.

**Comment by genavimex007** [comment]
I am trying to use this on silly tavern ( Currently: SillyTavern 1.12.6 'release' (ba6f7b7a9) ) and I am not seeing any kind of option to activiate the screen sharing or whichever, I installed it using the install extension, but from there it says that 'image inlining is turned off' but i dont see that option to turn it on anywhere. Any recommendations for a good image maker for a 1660ti card.

**Comment by Cohee1207** [comment]
Image inlining is a setting in the AI response configuration panel (leftmost icon).
